blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/crew-camufox/crew-camufox/discussions
    about: Ask questions and discuss with the community
  - name: 📚 Documentation
    url: https://crew-camufox.readthedocs.io
    about: Check our comprehensive documentation
  - name: 🔒 Security Issues
    url: mailto:security@crew-camufox.dev
    about: Report security vulnerabilities privately
